package(default_visibility = ["//visibility:public"])

cc_library(
    name = "harness_utils",
    hdrs = ["harness_utils.h"],
)

cc_library(
    name = "fuzzing_utils",
    hdrs = ["fuzzing_utils.h"],
    srcs = ["fuzzing_utils.cc"],
)
