package(default_visibility = ["//visibility:public"])

cc_library(
    name = "harness_utils",
    hdrs = ["entire_file_utils.h", "harness_utils.h"],
)

cc_library(
    name = "fuzzing_utils",
    hdrs = ["entire_file_utils.h", "fuzzing_utils.h"],
    srcs = ["fuzzing_utils.cc"],
)
