cc_test(
    name = "fuzztest_calculator",
    srcs = ["fuzztest_calculator.cc"],
    deps = [
        "@com_google_fuzztest//fuzztest",
        "@com_google_fuzztest//fuzztest:fuzztest_gtest_main",
        "@com_google_googletest//:gtest",
        "//main:calculator_lib",
    ],
)
